### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by matthawley** [JasperFx/lamar#112]
Upgraded to v2.0.1 to take in the fix for #104 however it still seems to be occurring when concurrent requests are executed resolving the same type.

Message: **An item with the same key has already been added.**
```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Lamar.IoC.Resolvers.ScopedResolver`1.Resolve(Scope scope)
at Lamar.IoC.Scope.GetInstance[T]()
```

**Comment by jeremydmiller** [comment]
Dunno, you're gonna have to give me repro steps

**Comment by matthawley** [comment]
I'll see if I can get a repro.

**Comment by jeremydmiller** [comment]
No new updates, I'm closing this
