### ISSUE TITLE
NRE when registering component with optional primitives as constructor parameters

### ISSUE THREAD

**Issue by mattiasnordqvist** [JasperFx/lamar#134]
Using Lamar 2.1.0, this code throws a NullReferenceException. I feel like it shouldn't... ?

```csharp
using Lamar;

namespace ConsoleApp8
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var container = new Container(x =>
            {
                x.For<IClock>().Use<Clock>();
            });
        }
    }

    public class Clock : IClock
    {
        public Clock(int hours = 24)
        {
        }
    }

    public interface IClock { }
}
```
```
Stacktrace:
   at Lamar.IoC.Instances.CtorArg..ctor(ParameterInfo parameter, Instance instance)
   at Lamar.IoC.Instances.ConstructorInstance.determineArgument(ServiceGraph services, ParameterInfo x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Lamar.IoC.Instances.ConstructorInstance.buildOutConstructorArguments(ServiceGraph services)
   at Lamar.IoC.Instances.ConstructorInstance.createPlan(ServiceGraph services)
   at Lamar.IoC.Instances.Instance.CreatePlan(ServiceGraph services)
   at Lamar.ServiceGraph.planResolutionStrategies()
   at Lamar.ServiceGraph.buildOutMissingResolvers()
   at LamarCompiler.Util.PerfTimer.Record(String text, Action action)
   at Lamar.ServiceGraph.Initialize(PerfTimer timer)
   at Lamar.IoC.Scope..ctor(IServiceCollection services, PerfTimer timer)
   at ConsoleApp8.Program.Main(String[] args) in C:\......\ConsoleApp8\Program.cs:line 9
```

**Comment by mattiasnordqvist** [comment]
Doing the same thing in a minimal ASP.NET web application like this

```csharp
 public void ConfigureContainer(ServiceRegistry services)
        {
            // Supports ASP.Net Core DI abstractions
            services.AddMvc();
            services.AddLogging();
            services.For<IClock>().Use<Clock>();
        }
```
And running it in IIS Express, gives me this buddy here instead
```
System.InvalidOperationException: 'Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])'
```

with no sign of Clocks, Lamar or nullreferences in the stack trace
```
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at WebApplication1.Program.Main(String[] args) in C:\...\WebApplication1\Program.cs:line 11
```

Not saying that this necessarily is a problem with Lamar, but just taking the Getting Started instructions  (https://jasperfx.github.io/lamar/getting_started/) and creating one single registration causes this, which gives a pretty bad impression.

**Comment by carl-berg** [comment]
I would argue that the latter case (with asp.net core) is worse because there's no hint of what the actual problem is. Very easy to get sidetracked on how to fix the problem. If nothing else a better exception (if possible) would be helpful in this case, but as there's no trace of the Lamar namespace in this stacktrace, i don't know if it is possible?

**Comment by jeremydmiller** [comment]
@mattiasnordqvist I'll get to this sometime in the next couple weeks, but the easiest way to fix it is to stop using optional constructor arguments, or register it like so:

    public class Program
    {
        public static void Main(string[] args)
        {
            var container = new Container(x =>
            {
                x.For<IClock>().Use(() => new Clock());
            });
        }
    }

    public class Clock : IClock
    {
        public Clock(int hours = 24)
        {
        }
    }

    public interface IClock { }

**Comment by sstrink** [comment]
@jeremydmiller I am still getting this error when I try to use the AspNetCore Healthchecks UI.  The 3.0 version fixed my issues on the original case, but this error still remains.  I got this error with 2.1 as well, but did not enter another bug because I found this one.  Link to my issue at the bottom.

Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Hosting.dll
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Hosting.dll
Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])


https://github.com/JasperFx/lamar/issues/135

**Comment by jeremydmiller** [comment]
@sstrink I don't think that's related to Lamar though. And I have tests in Lamar that build every possible registration in an aspnetcore with the health checks applied.

**Comment by mattiasnordqvist** [comment]
@sstrink Neither I think this is related actually. See this https://github.com/aspnet/Logging/issues/691

**Comment by sstrink** [comment]
A little confused by your post @mattiasnordqvist are you saying this is a MS issue or a Lamar issue?

**Comment by mattiasnordqvist** [comment]
Neither, really. My understanding is that their defaults are just incompatible. You have to "bridge" them by specifying to Lamar which LoggerFactory-constructor to use.
