### ISSUE TITLE
ASP.NET Core Identity - NotSupportedException thrown from InjectedServicesField.ToVariableExpression

### ISSUE THREAD

**Issue by inthegarden** [JasperFx/lamar#286]
ASP.NET Core MVC Web Application using .NET 5.0 - Identity added to an existing application as opposed to using the scaffolding feature.

**Packages**

Lamar 5.0.4
Microsoft.AspNetCore.Identity 2.2.0
Microsoft.AspNetCore.Identity.EntityFrameworkCore 5.0.7

**Register Identity in ConfigureContainer**

```
 serviceRegistry
                .AddIdentity<MyIdentityUser, MyIdentityRole>(options => options.SignIn.RequireConfirmedAccount = false)
                .AddEntityFrameworkStores<AuthIdentityDbContext>();
```

AddIdentity extension method (in Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions) contains the following code: -

![image](https://user-images.githubusercontent.com/22058115/123802824-9d1c8580-d8e3-11eb-9c43-2c0cb220bfb4.png)

AuthIdentityDbContext inherits from IdentityDbContext: -

```
AuthIdentityDbContext : IdentityDbContext<MyIdentityUser, MyIdentityRole, int>
```

**Exception**

Attempt to resolve the following types: -

```
UserManager<MyIdentityUser>
SignInManager<MyIdentityUser>
```

The following exception gets raised: -

```
System.NotSupportedException
Specified method is not supported.
   at Lamar.IoC.Frames.InjectedServiceField.ToVariableExpression(LambdaDefinition definition)
   at LamarCodeGeneration.Expressions.LambdaDefinition.ExpressionFor(Variable variable)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Lamar.IoC.Instances.InstanceConstructorFrame.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Frames.GetInstanceFrame.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Instances.FuncResolverDefinition.BuildResolver()
   at Lamar.IoC.Instances.GeneratedInstance.BuildFuncResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.Resolve(Scope scope)
   at (Closure`5 , Scope )
   at Lamar.IoC.Instances.GeneratedInstance.<>c__DisplayClass5_1.<BuildFuncResolver>b__0(Scope s)
   at Lamar.IoC.Instances.GeneratedInstance.Resolve(Scope scope)
   at (Closure`3 , Scope )
   at Lamar.IoC.Instances.GeneratedInstance.<>c__DisplayClass5_1.<BuildFuncResolver>b__0(Scope s)
   at Lamar.IoC.Instances.GeneratedInstance.Resolve(Scope scope)
   at (Closure`7 , Scope )
   at Lamar.IoC.Instances.GeneratedInstance.<>c__DisplayClass5_1.<BuildFuncResolver>b__0(Scope s)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.IoC.Scope.GetInstance[T]()
```

Appears to relate to the IdentityErrorDesciber type as shown in the following screenshot from the watch window: -

![image](https://user-images.githubusercontent.com/22058115/123802544-5595f980-d8e3-11eb-936b-a028c7c2a567.png)

**Comment by jeremydmiller** [comment]
@inthegarden "Works on my box", so there's something more going on in your setup. My repro steps are in the GH286 branch. If you can pull that branch down and add something to make the new test fail, that would help.

**Comment by inthegarden** [comment]
> @inthegarden "Works on my box", so there's something more going on in your setup. My repro steps are in the GH286 branch. If you can pull that branch down and add something to make the new test fail, that would help.

@jeremydmiller OK... I will pull it down and take a look. Thank you

**Comment by jeremydmiller** [comment]
@inthegarden The error you're getting is for Lamar trying to inline a singleton into the generated Func builders where the underlying registration isn't a singleton. Which I would have told you was impossible. Is there anyway you're changing the scope of something after it's registered? Like searching through the ServiceCollection and changing a scope? Sounds very unlikely, but that's all I've got so far.

**Comment by inthegarden** [comment]
@jeremydmiller Thank you for the extra info. For a bit of context; I am currently tasked with migrating a ASP.NET MVC .NET Framework 4.72 using StructureMap to ASP.NET MVC .NET 5.0 using Lamar. I haven't done anything like modifying scope but there's a fair bit of code and it's possible something's going on that I've yet to come across! :-) I have pulled down the GH286  branch and am working through that and identitfying differences between your code and mine. Will report back!

**Comment by inthegarden** [comment]
@jeremydmiller I have made some code modifications to branch GH286 and have managed to replicate the current state of the application I am working on. I using a IDesignTimeDbContextFactory<AuthIdentityDbContext> so that, in future, I can pick up a tenant specific connection string via an injected custom app configuration class.

I mistakenly had the factory (I had missed this factory out of the issue log above, apologies!) marked as Scoped, if it's Transient or Singleton everything fires as expected.

```
             services.For<AuthIdentityDbContext>()
                .Use(new DesignTimeDbContextFactory().CreateDbContext(Array.Empty<string>()))
                .Scoped();
```

I can push the code up if that's of any use? If so, where to?

**Comment by jeremydmiller** [comment]
@inthegarden If you want it to work as "scoped", you needed to make the registration a Lambda. Otherwise it's de facto a singleton. I'm adding some defensive coding to stop you from doing what you tried to do here:)

```
             services.For<AuthIdentityDbContext>()
                .Use(s => new DesignTimeDbContextFactory().CreateDbContext(Array.Empty<string>()))
                .Scoped();
```

**Comment by inthegarden** [comment]
:-) :-) Lovely, thanks @jeremydmiller!
