### ISSUE TITLE
Error: An item with the same key has already been added

### ISSUE THREAD

**Issue by nspyke** [JasperFx/lamar#90]
Occasionally I get this exception.
If I reload the page, it works without any errors or any code changes.

I'm running .NET Core 2.1.3.
Lamar v1.1.1

```
System.ArgumentException: An item with the same key has already been added. Key: 885546235
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass13_0.<ToResolver>b__0(Scope s)
   at Lamar.ServiceGraph.<>c__DisplayClass42_1.<FindResolver>b__0(Scope s)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.FileContentResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by CodingGorilla** [comment]
@nspyke Are you registering the HttpClientFactory or named HttpClients?  I get this same error, but not consistently, and it seems related to those two things.  But I haven't quite narrowed it down yet.

**Comment by erlendp** [comment]
I have narrowed the issue down to logging. If I do not make a call to LoggerFactory.AddConsole or LoggerFactory.AddDebug, then the error disappears. I imagine this is related to how Lamar is registering itself for logging.

Further investigation is required.

**Comment by CodingGorilla** [comment]
@erlendp I wonder if this wasn't resolved in [Lamar 1.1.2](https://www.nuget.org/packages/Lamar/1.1.2), have you tried to upgrade?  I was looking for the line of code mentioned in the stack trace and I can't find it anymore.

**Comment by erlendp** [comment]
@CodingGorilla The issue is still occurring with Lamar 1.1.2.

**Comment by CodingGorilla** [comment]
@erlendp Can you provide a new stack trace with the updated version?

**Comment by nspyke** [comment]
Hi @CodingGorilla 

Here's the new stack trace from 1.1.2.

```
System.ArgumentException: An item with the same key has already been added. Key: 850323360
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Lamar.Microsoft.DependencyInjection.LoggerInstance`1.resolveFromRoot(Scope root)
   at Lamar.ServiceGraph.<>c__DisplayClass42_1.<FindResolver>b__0(Scope s)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
```

**Comment by CodingGorilla** [comment]
I wonder if this isn't a concurrency issue where the logger is getting created and stored on a different thread, while this thread is also attempting to resolve the logger.  

@jeremydmiller Any thoughts on this?  Do we need to add some locking to the scope's services?

**Comment by jeremydmiller** [comment]
@CodingGorilla @nspyke I'm adding some locking in the special Logger, Options, OptionsSnapshot instances to address this. Will be in 1.2.0.
